In [1]:
import numpy as np

In [5]:
#Normalization Problem
x = np.random.rand(5, 5)
x_normalized = (x - x.mean()) / x.std()

np.save ("x_normalize.npy", x_normalized)

print("Original x: \n", x)
print("\nNormalized x: \n", x_normalized)


Original x: 
 [[0.98312072 0.55754224 0.54324473 0.80626609 0.95371957]
 [0.39788673 0.84075112 0.36706528 0.89294645 0.94374134]
 [0.93058163 0.6579099  0.28755047 0.46115133 0.47171002]
 [0.56402217 0.05587221 0.93059603 0.52263247 0.60484175]
 [0.86216992 0.71035308 0.31826535 0.53833428 0.39075981]]

Normalized x: 
 [[ 1.45326658 -0.26760189 -0.32541529  0.73813746  1.33438012]
 [-0.91318467  0.87758107 -1.03781423  1.08863803  1.29403217]
 [ 1.2408196   0.13824459 -1.35934018 -0.65736803 -0.61467292]
 [-0.24139968 -2.29615401  1.24087783 -0.40876298 -0.07634167]
 [ 0.96419011  0.35030376 -1.23514154 -0.34527117 -0.94200305]]


In [6]:
#Divisible by 3 Problem
x = np.arange(1, 101)
squares = x ** 2
A = squares.reshape(10, 10)
div = A[A % 3 == 0]
np.save("div", div)

In [7]:
print("10 x 10 ndarray of squares: \n", A)
print("\nElement divisible by 3: \n", div)

10 x 10 ndarray of squares: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Element divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
